// Code generated by tools/genmodules. DO NOT EDIT.
//
// 由 `make generate`（或 go generate ./app）扫描 modules/ 得到，只有这一个来源。
// 想装一个模块就把它的目录复制进 modules/、重新编译；不要手工编辑本文件。
//
// 发行版的模块**不在这里**：它是另一个 Go module，把自己那张表交给
// app.Selection（见 docs/09-extension-guide.md §8）。

package app

import (
	modules "github.com/rzbdz/newgate/component"
	mod_breaker "github.com/rzbdz/newgate/modules/breaker"
	mod_cli "github.com/rzbdz/newgate/modules/cli"
	mod_config "github.com/rzbdz/newgate/modules/config"
	mod_confighook "github.com/rzbdz/newgate/modules/confighook"
	mod_entry "github.com/rzbdz/newgate/modules/entry"
	mod_gateway "github.com/rzbdz/newgate/modules/gateway"
	mod_pluginmanager "github.com/rzbdz/newgate/modules/pluginmanager"
	mod_runtime "github.com/rzbdz/newgate/modules/runtime"
	mod_thinking "github.com/rzbdz/newgate/modules/thinking"
	mod_wrapper "github.com/rzbdz/newgate/modules/wrapper"
)

// coreModules 是内核自带的组件表，按目录名排序。
//
// Dir 与 Component 必须成对出现：目录名是「关掉哪一个」的键（见 app.Selection），
// 组件名不必与它相同（发行版里就有：claudecode_deepseek → claudecode-deepseek）。
// 内核这一侧今天恰好个个同名，那是巧合、不是规矩。
func coreModules() []Entry {
	return []Entry{
		{Dir: "breaker", Component: mod_breaker.New()},
		{Dir: "cli", Component: mod_cli.New()},
		{Dir: "config", Component: mod_config.New()},
		{Dir: "confighook", Component: mod_confighook.New()},
		{Dir: "entry", Component: mod_entry.New()},
		{Dir: "gateway", Component: mod_gateway.New()},
		{Dir: "pluginmanager", Component: mod_pluginmanager.New()},
		{Dir: "runtime", Component: mod_runtime.New()},
		{Dir: "thinking", Component: mod_thinking.New()},
		{Dir: "wrapper", Component: mod_wrapper.New()},
	}
}

// generatedComponents 是内核自己那张图要装的组件。
// 顺序不是依赖声明——真实启动顺序由 capability 依赖图在构图期计算。
func generatedComponents() []modules.Component {
	out := make([]modules.Component, 0, 10)
	for _, e := range coreModules() {
		out = append(out, e.Component)
	}
	return out
}
