// Command genmodules 在构建期扫描 go/modules/，生成组合根要装配的组件清单。
//
// 为什么要有这一步
//
// 组合根以前手工维护一份 `config.New(), gateway.New(), …` 的列表。想装一个
// 模块就得改这行清单——而清单本身不携带任何信息，纯粹是「有哪些目录」的
// 手工副本：加目录、加 import、加调用，三处都要动，漏一处就是编译错误或者
// 更糟的「模块在仓库里但没被装配」。
//
// 所以规则改成：modules/ 下每个含根 module.go 并导出 New() 的目录都是一个
// 组件，清单由本工具扫描生成。装模块 = 把目录复制进来、重新编译。
//
// 判据刻意收得很紧——目录里有 module.go **且**它导出 `func New() modules.Component`
// 才算组件。这让我们能在 modules/ 下放纯实现子包（gateway/forward 之类），
// 而不会被误当成组件。
//
// # 清单只有一个来源：本仓库（2026-09-20 起）
//
// 直到 2026-09-20，这里还有第二个来源：仓库根的 modules-ext.json（一张 Pin）
// 指向一个发行版仓库，构建期把它 clone 到 go/modules-ext/ 再扫一遍。那条路已经
// 整个删掉了，因为它让**产品决定住在内核里**，代价实测有三条：编一次发行版就把
// 内核 checkout 改脏（生成的清单被重写成发行版的装配清单，挡住 pull/换分支）；
// 内核 CI 必须去 clone 另一个仓库；内核的构建因此不再离线。
//
// 现在发行版是**另一个 Go module**（`replace` 回本仓库），它拿 app.Selection
// 把自己那张表交给内核的组合根——「装哪些模块」是产品决定，归发行版；内核只
// 需要说清「我有哪几个」（coreModules()，带目录名），并让消费者能按目录名关掉
// 其中几个。判据与理由见 docs/09-extension-guide.md §8。
//
// 于是本工具**完全离线**：不需要网络，不需要另一个仓库在场。它生成两样东西，
// 区别是给谁看：
//
//	coreModules()         内核自带的组件表（带目录名）——给消费者看
//	generatedComponents() 内核自己那张图要装的组件——给组合根看
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path"
	"path/filepath"

	modscan "github.com/rzbdz/newgate/go/tools/genmodules/scan"
)

const (
	modulesRelDir = "modules"
	genFileName   = "modules_gen.go"
)

// module 是一个待装配的组件目录。
type module struct {
	dir   string // modules/ 下的目录名，用于日志与查重
	path  string // 相对 go/ 的 import 路径后缀（`modules/foo`）
	alias string // 生成的 import 别名，统一前缀避免与局部变量撞名
}

func main() {
	check := flag.Bool("check", false,
		"只校验生成结果是否与当前源码一致，不写文件（测试用）")
	flag.Parse()

	root, err := moduleRoot()
	if err != nil {
		fail(err)
	}
	modules, err := scan(filepath.Join(root, modulesRelDir))
	if err != nil {
		fail(err)
	}
	// 生成物必须**自己**就是 gofmt 干净的：`make check-fmt` 在 CI 里独立跑，
	// 一个没对齐的 import 块会让它红，而报的是「格式不对」——离真因（别名长度
	// 变了）隔着好几步。所以这里不靠手写缩进碰运气，直接过一遍 go/format。
	content, err := format.Source(render(modules))
	if err != nil {
		fail(fmt.Errorf("生成的源码不合法（这是生成器的 bug）: %w", err))
	}
	target := filepath.Join(root, "app", genFileName)

	if *check {
		current, err := os.ReadFile(target)
		if err != nil || !bytes.Equal(current, content) {
			fail(fmt.Errorf("%s 已过期：运行 `make generate`（或 go generate ./app）后重新提交", target))
		}
		return
	}
	if err := os.WriteFile(target, content, 0o644); err != nil {
		fail(err)
	}
	fmt.Printf("genmodules: %d 个组件 → %s\n", len(modules), target)
}

// moduleRoot 从当前工作目录向上找到含 go.mod 的目录。
// `go generate` 在包目录（app/）里跑，`go run ./tools/genmodules` 在 module
// 根跑，两种调用点都要能工作，所以靠 go.mod 而不是相对路径定位。
func moduleRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("向上找不到 go.mod（从 %s 开始）", dir)
		}
		dir = parent
	}
}

// scan 列出 componentsDir 下所有「是组件」的目录名，按字母序返回。
// 字母序而非目录遍历序：生成结果必须与文件系统返回顺序无关，
// 否则不同机器上 diff 会飘。
func scan(componentsDir string) ([]module, error) {
	names, err := modscan.Dirs(componentsDir)
	if err != nil {
		return nil, err
	}
	out := make([]module, 0, len(names))
	for _, name := range names {
		// 约定：目录名里的下划线在 import 别名里保留（Go 标识符允许下划线）
		rel := path.Join(modulesRelDir, name)
		out = append(out, module{dir: name, path: rel, alias: modscan.Ident("mod_", name)})
	}
	return out, nil
}

// render 生成组件清单源码。
func render(modules []module) []byte {
	const importPath = "github.com/rzbdz/newgate/go"

	var b bytes.Buffer
	b.WriteString("// Code generated by tools/genmodules. DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// 由 `make generate`（或 go generate ./app）扫描 modules/ 得到，只有这一个来源。\n")
	b.WriteString("// 想装一个模块就把它的目录复制进 modules/、重新编译；不要手工编辑本文件。\n")
	b.WriteString("//\n")
	b.WriteString("// 发行版的模块**不在这里**：它是另一个 Go module，把自己那张表交给\n")
	b.WriteString("// app.Selection（见 docs/09-extension-guide.md §8）。\n")
	b.WriteString("\npackage app\n\n")
	b.WriteString("import (\n")
	b.WriteString("\tmodules \"" + importPath + "/component\"\n")
	for _, m := range modules {
		fmt.Fprintf(&b, "\t%s \"%s/%s\"\n", m.alias, importPath, m.path)
	}
	b.WriteString(")\n\n")
	b.WriteString("// coreModules 是内核自带的组件表，按目录名排序。\n")
	b.WriteString("//\n")
	b.WriteString("// Dir 与 Component 必须成对出现：目录名是「关掉哪一个」的键（见 app.Selection），\n")
	b.WriteString("// 而三个模块的目录名与组件名并不相同（claudecode_deepseek → claudecode-deepseek）。\n")
	b.WriteString("func coreModules() []Entry {\n")
	b.WriteString("\treturn []Entry{\n")
	for _, m := range modules {
		fmt.Fprintf(&b, "\t\t{Dir: %q, Component: %s.New()},\n", m.dir, m.alias)
	}
	b.WriteString("\t}\n}\n\n")
	b.WriteString("// generatedComponents 是内核自己那张图要装的组件。\n")
	b.WriteString("// 顺序不是依赖声明——真实启动顺序由 capability 依赖图在构图期计算。\n")
	b.WriteString("func generatedComponents() []modules.Component {\n")
	fmt.Fprintf(&b, "\tout := make([]modules.Component, 0, %d)\n", len(modules))
	b.WriteString("\tfor _, e := range coreModules() {\n")
	b.WriteString("\t\tout = append(out, e.Component)\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn out\n}\n")
	return b.Bytes()
}

// fail 是生成器的出口：一句话说清哪里错，退出码 1。
func fail(err error) {
	fmt.Fprintln(os.Stderr, "genmodules:", err)
	os.Exit(1)
}
