// Command genmodules 在构建期扫描 go/modules/，生成组合根要装配的组件清单。
//
// 为什么要有这一步
//
// 组合根以前手工维护一份 `config.New(), gateway.New(), …` 的列表。想装一个
// 模块就得改这行清单——而清单本身不携带任何信息，纯粹是「有哪些目录」的
// 手工副本：加目录、加 import、加调用，三处都要动，漏一处就是编译错误或者
// 更糟的「模块在仓库里但没被装配」。
//
// 所以规则改成：modules/ 下每个含根 module.go 并导出 New() 的目录都是一个
// 组件，清单由本工具扫描生成。装模块 = 把目录复制进来、重新编译。
//
// 判据刻意收得很紧——目录里有 module.go **且**它导出 `func New() modules.Component`
// 才算组件。这让我们能在 modules/ 下放纯实现子包（gateway/forward 之类），
// 而不会被误当成组件。
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	modulesRelDir = "modules"
	genFileName   = "modules_gen.go"
)

// module 是一个待装配的组件目录。
type module struct {
	dir   string // modules/ 下的目录名，也是默认的 import 别名后缀
	alias string // 生成的 import 别名，统一前缀避免与局部变量撞名
}

func main() {
	check := flag.Bool("check", false,
		"只校验生成结果是否与当前源码一致，不写文件（测试用）")
	flag.Parse()

	root, err := moduleRoot()
	if err != nil {
		fail(err)
	}
	modules, err := scan(filepath.Join(root, modulesRelDir))
	if err != nil {
		fail(err)
	}
	content := render(modules)
	target := filepath.Join(root, "app", genFileName)

	if *check {
		current, err := os.ReadFile(target)
		if err != nil || !bytes.Equal(current, content) {
			fail(fmt.Errorf("%s 已过期：运行 `make generate`（或 go generate ./app）后重新提交", target))
		}
		return
	}
	if err := os.WriteFile(target, content, 0o644); err != nil {
		fail(err)
	}
	fmt.Printf("genmodules: %d 个组件 → %s\n", len(modules), target)
}

// moduleRoot 从当前工作目录向上找到含 go.mod 的目录。
// `go generate` 在包目录（app/）里跑，`go run ./tools/genmodules` 在 module
// 根跑，两种调用点都要能工作，所以靠 go.mod 而不是相对路径定位。
func moduleRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("向上找不到 go.mod（从 %s 开始）", dir)
		}
		dir = parent
	}
}

// scan 列出 componentsDir 下所有「是组件」的目录名，按字母序返回。
// 字母序而非目录遍历序：生成结果必须与文件系统返回顺序无关，
// 否则不同机器上 diff 会飘。
func scan(componentsDir string) ([]module, error) {
	entries, err := os.ReadDir(componentsDir)
	if err != nil {
		return nil, err
	}
	var out []module
	for _, entry := range entries {
		if !entry.IsDir() || strings.HasPrefix(entry.Name(), ".") {
			continue
		}
		name := entry.Name()
		// 约定：目录名里的下划线在 import 别名里保留（Go 标识符允许下划线）
		if !isComponent(filepath.Join(componentsDir, name, "module.go")) {
			continue
		}
		out = append(out, module{dir: name, alias: "mod_" + name})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].dir < out[j].dir })
	return out, nil
}

// isComponent 判断一个 module.go 是否导出 `func New() modules.Component`。
// 只解析不编译：这一步在构建之前跑，不能依赖源码当时能通过类型检查。
func isComponent(path string) bool {
	file, err := parser.ParseFile(token.NewFileSet(), path, nil, parser.SkipObjectResolution)
	if err != nil {
		return false
	}
	for _, decl := range file.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if !ok || fn.Name.Name != "New" || fn.Recv != nil {
			continue
		}
		results := fn.Type.Results
		if results == nil || len(results.List) != 1 {
			continue
		}
		sel, ok := results.List[0].Type.(*ast.SelectorExpr)
		if !ok || sel.Sel.Name != "Component" {
			continue
		}
		return true
	}
	return false
}

// render 生成组件清单源码。生成物本身也要 gofmt 干净，见下面手写的缩进。
func render(modules []module) []byte {
	const importPath = "github.com/rzbdz/newgate/go"

	var b bytes.Buffer
	b.WriteString("// Code generated by tools/genmodules. DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// 这里的内容由 `make generate`（或 go generate ./app）扫描 modules/ 得到。\n")
	b.WriteString("// 想装一个模块就把它的目录复制进 modules/、重新编译；不要手工编辑本文件。\n")
	b.WriteString("\npackage app\n\n")
	b.WriteString("import (\n")
	b.WriteString("\tmodules \"" + importPath + "/component\"\n")
	for _, m := range modules {
		fmt.Fprintf(&b, "\t%s \"%s/modules/%s\"\n", m.alias, importPath, m.dir)
	}
	b.WriteString(")\n\n")
	b.WriteString("// generatedComponents 是扫描 modules/ 得到的装配清单。\n")
	b.WriteString("// 顺序不是依赖声明——真实启动顺序由 capability 依赖图在构图期计算。\n")
	b.WriteString("func generatedComponents() []modules.Component {\n")
	b.WriteString("\treturn []modules.Component{\n")
	for _, m := range modules {
		fmt.Fprintf(&b, "\t\t%s.New(),\n", m.alias)
	}
	b.WriteString("\t}\n}\n")
	return b.Bytes()
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "genmodules:", err)
	os.Exit(1)
}
