package i18n

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// 两种文件、一套解析：
//
//	账本 catalogs/ledger.json   生成物（tools/i18n extract 写、-check 校验）。
//	                            记「源码里有哪些消息、各在哪、带什么实参」。
//	译文 catalogs/<lang>.json   翻译表。键就是源语言原文。
//
// 为什么账本是生成物而译文不是：账本能从源码**推**出来（推错了就是 bug，该在 CI
// 里红），译文推不出来（那是人的产出，只能由工具**追加**，绝不能覆盖人写的东西）。

// 译文文件长这样（键排序、稳定输出，方便 diff 与 review）：
//
//	{
//	  "meta": { "language": "zh-Hans", "source": "en", "widths": { "label": 8 } },
//	  "messages": {
//	    "Proxy": "代理",
//	    "Saved {n} file": { "one": "已保存 {n} 个文件", "other": "已保存 {n} 个文件",
//	                        "machine": true, "reviewed": false },
//	    "Kept {n} keys": { "text": "保留 {n} 个键", "note": "给译者看的上下文" }
//	  }
//	}
//
// 一条译文只有正文时写成**裸字符串**（绝大多数都是），需要复数/备注/机翻标记时
// 才写成对象——文件读起来像一份对照表，而不是一堆样板字段。
type fileJSON struct {
	Meta     metaJSON                   `json:"meta"`
	Messages map[string]json.RawMessage `json:"messages"`
}

type metaJSON struct {
	Language string         `json:"language"`
	Source   string         `json:"source,omitempty"`
	Widths   map[string]int `json:"widths,omitempty"`
}

type entryJSON struct {
	Text     string `json:"text,omitempty"`
	One      string `json:"one,omitempty"`
	Other    string `json:"other,omitempty"`
	Note     string `json:"note,omitempty"`
	Machine  bool   `json:"machine,omitempty"`
	Reviewed bool   `json:"reviewed,omitempty"`
}

// 账本文件：键是源语言原文，值只记「在哪、带什么实参、复数怎么写、人写的备注」。
// 它**不含译文**——源语言的文本就是源码里那一句，抄一份进来必然对不上。
type ledgerJSON struct {
	Note     string                     `json:"note"`
	Messages map[string]ledgerEntryJSON `json:"messages"`
}

type ledgerEntryJSON struct {
	Where string   `json:"where"`
	Args  []string `json:"args,omitempty"`
	Other string   `json:"other,omitempty"` // 复数消息的复数形式
	Note  string   `json:"note,omitempty"`  // 人写的，extract 不许覆盖
}

// ParseCatalog 解一份**译文**。字段名写错会报错（DisallowUnknownFields）：
// 一行拼错的 `"machien": true` 若被静默忽略，症状是「我明明标了机翻，怎么没标上」。
func ParseCatalog(raw []byte) (Catalog, error) {
	dec := json.NewDecoder(bytes.NewReader(raw))
	dec.DisallowUnknownFields()
	var f fileJSON
	if err := dec.Decode(&f); err != nil {
		return Catalog{}, fmt.Errorf("译文文件解不出来: %w", err)
	}
	if f.Meta.Language == "" {
		return Catalog{}, fmt.Errorf("译文文件没有 meta.language")
	}
	out := Catalog{
		Language: f.Meta.Language,
		Source:   f.Meta.Source,
		Widths:   f.Meta.Widths,
		Messages: make(map[string]Entry, len(f.Messages)),
	}
	for id, rawEntry := range f.Messages {
		e, err := parseEntry(rawEntry)
		if err != nil {
			return Catalog{}, fmt.Errorf("消息 %q: %w", id, err)
		}
		out.Messages[id] = e
	}
	return out, nil
}

func parseEntry(raw json.RawMessage) (Entry, error) {
	trimmed := bytes.TrimSpace(raw)
	if len(trimmed) == 0 {
		return Entry{}, fmt.Errorf("空条目")
	}
	if trimmed[0] == '"' {
		var s string
		if err := json.Unmarshal(trimmed, &s); err != nil {
			return Entry{}, err
		}
		return Entry{Text: s}, nil
	}
	var ej entryJSON
	dec := json.NewDecoder(bytes.NewReader(trimmed))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&ej); err != nil {
		return Entry{}, err
	}
	if ej.Text == "" && ej.One == "" && ej.Other == "" {
		return Entry{}, fmt.Errorf("条目里既没有 text 也没有 one/other")
	}
	return Entry{
		Text: ej.Text, One: ej.One, Other: ej.Other,
		Note: ej.Note, Machine: ej.Machine, Reviewed: ej.Reviewed,
	}, nil
}

// MarshalCatalog 渲染译文文件（键排序：map 遍历序随机会让每次生成的 diff 都飘，
// 同 tools/genmodules 那条理由）。
func MarshalCatalog(c Catalog) ([]byte, error) {
	f := fileJSON{
		Meta:     metaJSON{Language: c.Language, Source: c.Source, Widths: c.Widths},
		Messages: make(map[string]json.RawMessage, len(c.Messages)),
	}
	for id, e := range c.Messages {
		raw, err := marshalEntry(e)
		if err != nil {
			return nil, fmt.Errorf("消息 %q: %w", id, err)
		}
		f.Messages[id] = raw
	}
	return encode(f)
}

func marshalEntry(e Entry) (json.RawMessage, error) {
	if !e.plural() && e.Note == "" && !e.Machine && !e.Reviewed {
		return json.Marshal(e.Text)
	}
	return json.Marshal(entryJSON{
		Text: e.Text, One: e.One, Other: e.Other,
		Note: e.Note, Machine: e.Machine, Reviewed: e.Reviewed,
	})
}

// ParseLedger 解账本。
func ParseLedger(raw []byte) (Ledger, error) {
	var f ledgerJSON
	dec := json.NewDecoder(bytes.NewReader(raw))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&f); err != nil {
		return Ledger{}, fmt.Errorf("账本解不出来: %w", err)
	}
	out := Ledger{Messages: make(map[string]LedgerEntry, len(f.Messages))}
	for id, e := range f.Messages {
		out.Messages[id] = LedgerEntry{Where: e.Where, Args: e.Args, Other: e.Other, Note: e.Note}
	}
	return out, nil
}

// MarshalLedger 渲染账本（同样是键排序 + 定长缩进）。
func MarshalLedger(l Ledger) ([]byte, error) {
	f := ledgerJSON{
		Note:     "Generated by tools/i18n extract. Do not edit by hand — change the T(...) call in the source instead.",
		Messages: make(map[string]ledgerEntryJSON, len(l.Messages)),
	}
	for id, e := range l.Messages {
		f.Messages[id] = ledgerEntryJSON{Where: e.Where, Args: e.Args, Other: e.Other, Note: e.Note}
	}
	return encode(f)
}

func encode(v any) ([]byte, error) {
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false) // 文案里会有 < > &，转义成 &lt; 就没法读了
	enc.SetIndent("", "  ")
	if err := enc.Encode(v); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// OverlayDir 是磁盘覆盖的目录：`<root>/locale/`。
//
// 为什么允许覆盖：翻译是**最容易被使用者当场发现错误**的东西（一句别扭的译文，
// 用户比译者更早看到）。让他改一个 JSON 就生效，比让他等下一版强——这也是这个
// 项目一贯的路子（mappings/ 丢个 .kv 就生效）。
func OverlayDir(root string) string { return filepath.Join(root, "locale") }

// OverlayPath 是某个语言覆盖文件的位置。
func OverlayPath(dir, tag string) string { return filepath.Join(dir, tag+".json") }

// readOverlay 读磁盘覆盖。文件不存在、读不动、解不出来都**不报错**：它是一条
// 锦上添花的路，坏了不该挡住启动。但解不出来要留一条提示——静默忽略会让
// 「我改了怎么没生效」变成一次无解的排查。
func readOverlay(dir, tag string) (Catalog, bool) {
	if dir == "" || tag == "" {
		return Catalog{}, false
	}
	raw, err := os.ReadFile(OverlayPath(dir, tag))
	if err != nil {
		return Catalog{}, false
	}
	c, err := ParseCatalog(raw)
	if err != nil {
		fmt.Fprintf(os.Stderr, "newgate: 忽略解不出来的语言覆盖 %s: %v\n", OverlayPath(dir, tag), err)
		return Catalog{}, false
	}
	c.Builtin = false
	return c, true
}

// placeholderName 判 `{...}` 里那个词是不是**占位符名字**：标识符形状才算。
//
// 为什么不能见了花括号就当占位符：文案里会出现**机器标记**，而 JSON 自己就带
// 花括号——`injected thinking:{"type":"disabled"} ({why})` 里那对花括号是请求体
// 的字节，不是待填的槽。按标识符形状判，两者永远不会打架；实参名本来就是 Go
// 那边写字面量的键，标识符形状是它们的自然约定（见 A 类型的注释）。
func placeholderName(s string) bool {
	if s == "" {
		return false
	}
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case c == '_' || ('a' <= c && c <= 'z') || ('A' <= c && c <= 'Z'):
		case '0' <= c && c <= '9':
			if i == 0 {
				return false
			}
		default:
			return false
		}
	}
	return true
}

// Placeholders 取一句文案里的占位符名字（去重、排序）。
//
// 它有两个用户：tools/i18n 检查「译文与源文的占位符集合一致」（漏了 `{dir}` 就是
// 一条坏消息——界面上会永远显示 `{dir}`），以及检查调用点给的实参对不对得上。
func Placeholders(text string) []string {
	seen := map[string]bool{}
	for i := 0; i < len(text); {
		if text[i] != '{' {
			i++
			continue
		}
		end := strings.IndexByte(text[i:], '}')
		if end < 0 {
			break
		}
		name := text[i+1 : i+end]
		if placeholderName(name) {
			seen[name] = true
		}
		i += end + 1
	}
	out := make([]string, 0, len(seen))
	for k := range seen {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// EntryPlaceholders 取一条译文全部形式（含单复数）里的占位符并集。
func EntryPlaceholders(e Entry) []string {
	seen := map[string]bool{}
	for _, t := range []string{e.Text, e.One, e.Other} {
		for _, p := range Placeholders(t) {
			seen[p] = true
		}
	}
	out := make([]string, 0, len(seen))
	for k := range seen {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// SortedKeys 把一个消息表（账本或译文）的键排好序。
func SortedKeys[T any](m map[string]T) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
