// Code generated by tools/genmodules. DO NOT EDIT.
//
// 这里的内容由 `make generate`（或 go generate ./app）扫描 modules/ 得到。
// 想装一个模块就把它的目录复制进 modules/、重新编译；不要手工编辑本文件。

package app

import (
	modules "github.com/rzbdz/newgate/go/component"
	mod_claudecode "github.com/rzbdz/newgate/go/modules/claudecode"
	mod_claudecode_deepseek "github.com/rzbdz/newgate/go/modules/claudecode_deepseek"
	mod_claudecode_glm "github.com/rzbdz/newgate/go/modules/claudecode_glm"
	mod_cli "github.com/rzbdz/newgate/go/modules/cli"
	mod_config "github.com/rzbdz/newgate/go/modules/config"
	mod_confighook "github.com/rzbdz/newgate/go/modules/confighook"
	mod_deepseek "github.com/rzbdz/newgate/go/modules/deepseek"
	mod_gateway "github.com/rzbdz/newgate/go/modules/gateway"
	mod_glm "github.com/rzbdz/newgate/go/modules/glm"
	mod_opencode "github.com/rzbdz/newgate/go/modules/opencode"
	mod_opencodeomo "github.com/rzbdz/newgate/go/modules/opencodeomo"
	mod_runtime "github.com/rzbdz/newgate/go/modules/runtime"
	mod_thinking "github.com/rzbdz/newgate/go/modules/thinking"
	mod_wrapper "github.com/rzbdz/newgate/go/modules/wrapper"
)

// generatedComponents 是扫描 modules/ 得到的装配清单。
// 顺序不是依赖声明——真实启动顺序由 capability 依赖图在构图期计算。
func generatedComponents() []modules.Component {
	return []modules.Component{
		mod_claudecode.New(),
		mod_claudecode_deepseek.New(),
		mod_claudecode_glm.New(),
		mod_cli.New(),
		mod_config.New(),
		mod_confighook.New(),
		mod_deepseek.New(),
		mod_gateway.New(),
		mod_glm.New(),
		mod_opencode.New(),
		mod_opencodeomo.New(),
		mod_runtime.New(),
		mod_thinking.New(),
		mod_wrapper.New(),
	}
}
